
services:
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqldb
    environment:
      SA_PASSWORD: "EarlTest12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mssqldb
    environment:
      # Override ASPNETCORE_URLS so it listens on port 80
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Server=mssqldb;Database=BookingDb;User Id=sa;Password=EarlTest12345;TrustServerCertificate=True;"
      Jwt__Key: "9Jk3Pm8RzL4vT7yHgQ2bX5nD0uW1fE6Y"
    ports:
      - "5000:80"
    networks:
      - app-network

  angular-app:
    build:
      context: ./front-end/angular-app
      dockerfile: Dockerfile
    container_name: angular-app
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge