version: '3.8'

services:
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqldb
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: dotnet-backend
    ports:
      - "5000:80"
    depends_on:
      - mssqldb
    networks:
      - app-network

  angular-app:
    build: ./angular-app
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
